apiVersion: apps/v1
kind: Deployment
metadata:
  name: simple-http-jvm
  labels:
    app: simple-http-jvm
spec:
  replicas: 3
  selector:
    matchLabels:
      app: simple-http-jvm
  template:
    metadata:
      labels:
        app: simple-http-jvm
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: '/metrics'
        prometheus.io/port: '9999'
    spec:
      containers:
      - name: simple-http-jvm
        image: terrywong002/simple-http-jvm-metrics:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 9999
---
apiVersion: v1
kind: Service
metadata:
  name: simple-http-jvm
spec:
  selector:
    app: simple-http-jvm
  ports:
    - port: 9999
      targetPort: 9999
  type: NodePort